### PR TITLE
[r] Better must_fail 

### PR DESCRIPTION
**Pull request by catriuspham**
### Related issue
https://github.com/EastAgile/robber.py/issues/53

### Description
Now, a `must_fail` test only passes if all of the expectations inside of it pass

### Usage

This fails:

```python
@must_fail
def test_eq_failure(self):
    expect(1).to.eq(2)
    expect(1).to.eq(1)
```

This passes:
```python
@must_fail
def test_eq_failure(self):
    expect(1).to.eq(2)
    expect(1).to.eq(3)
```

### Other changes

- Make BadExpectation handles the failure messages' color
- A must_fail test can be run alone and directly with `nose`.

### CODE REVIEW

**Comment by catriuspham** [comment]
@nhanho You helped a lot with the logic of this PR. Thanks.

**Comment by catriuspham** [comment]
@hieueastagile Please take a look

**Comment by hieueastagile** [comment]
LGTM @catriuspham

**Comment by catriuspham** [comment]
@oyster Please merge this PR and close this issue https://github.com/EastAgile/robber.py/issues/53

**Pull request merged**
