### PR TITLE
[r] Improve diffs, fix mock matchers won't work properly when there are only kwargs

### PR DESCRIPTION
**Pull request by catriuspham**
### Related issues

https://github.com/EastAgile/robber.py/issues/60
https://github.com/EastAgile/robber.py/issues/61

### Description

The title says it all

### Changes
- New diffs for format for dict
```python
Diffs:
A['a'] = 'Some super long text that makes your eyes bleed so bad that you want to die' 
B['a'] = 'Some super long text that makes your eyes bleed so bad that you don't want to live anymore'
```

- `MockMixin` is added to replace current `Helper`

### Notes
- This PR does not contain multilevel diffs. We will consider implementing it or not later.

### CODE REVIEW

**Comment by catriuspham** [comment]
@hieueastagile I know that you are really busy, but there're too many unmerged PRs... Please take a look at this one also.

**Comment by catriuspham** [comment]
@nhanbt This will make the `called_once_with` work :muscle:

**Review by hieueastagile — COMMENTED** [review]
Cool! Let's merge this @catriuspham

**Comment by catriuspham** [comment]
@oyster Please help merge this PR thanks.

**Comment by catriuspham** [comment]
@oyster and close these following issues: https://github.com/EastAgile/robber.py/issues/60, https://github.com/EastAgile/robber.py/issues/61

**Comment by hieueastagile** [comment]
If you are the one who opened it, you can close it too @catriuspham :P.

**Comment by catriuspham** [comment]
@hieueastagile Now I notice that 😮  Thanks for reminding.

**Pull request merged**
